### ISSUE TITLE
OpenGL deprecation in future iOS versions

### ISSUE THREAD

**Issue by dragonikpl** [mousebird/WhirlyGlobe#1072]
Are there any plans for moving WhirlyGlobe from OpenGL to Metal, as latest news from WWDC are that OpenGL will be deprecated in future OS.

**Comment by dragonikpl** [comment]
Confirmation: https://reddit.app.link/NhZgrbSlvN

**Comment by saildronesteve** [comment]
YES!  As I tweeted yesterday, we will move WhirlyGlobe-Maply to Metal.  The issue was always money.

We'll either do it here at my current job or I'll make arrangements outside of that.

I'm actually pretty excited about Metal.  Much as I love the openness of OpenGL ES, it's become difficult to do things we like to do in WhirlyGlobe-Maply.  Multi-threading is pretty painful.  But we did all that and so moving to Metal is going to be a breeze.

And no wrapper toolkits on top of Metal.  All respect to the people doing those, but I want to be using the fastest, best interface on every platform.  On iOS that's Metal.  On Android it'll continue to be OpenGL ES for a while.

That future version will be faster and use less power.  If you have your own shaders.... you'll have to rewrite your own shaders.  Not that many do.  Most people won't see any difference.
