### ISSUE TITLE
[iOS] Fading Out Vector Objects II

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1178]
Hello,

I have a little problem with Vector-Objects again. When I fade them out over time, the shader doesn’t really seem to support that, because there are stripes occurring that I think the shader should handle.

I added a short clip, to show what I’m talking about. [ShortClip](http://sendvid.com/9na5vyig)

Also in the first few seconds of the video, when the globes borders are still visible, the underlying map (yellow) is visible through the blue VectorObjects. I hope you get what I mean there.  Is there a way to fix that?

I appreciate WhirlyGlobe and your support a lot. Thank you!

**Comment by mousebird** [comment]
The problem is in the triangulation.  When the geometry has no fade, it's not obvious.

You can try breaking down large objects into a grid before they're tessellated.  That tends to work better on the globe.

Take a look at the TextureVectorTestCase.  The comments explain this approach in more detail.
