### ISSUE TITLE
Path definition

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#241]
Hi, in WhirlyGlobeLib/src/GridClipper.mm, there are references to a 'Path' class or type.  

I'm now upgrading my WhirlyGlobe submodule to 2.3.1, and so I'm seeing this for the first time.  I'm getting an error on compile: "Use of undeclared identifier 'Path'".

I looked in WhirlyGlobeSrc and third-party but couldn't find the type definition, except in certain templates which don't seem to apply to the code in question.

Do you know where Path is defined?

**Comment by marcusficner** [comment]
When using submodules clipper comes with version 6.1.3a from here: https://github.com/mousebird/clipper/tree/99db07b4aacf3f4f2df88853636dcf683d70ec86/cpp.

Installing WhirlyGlobe via CocoaPods installs clipper 5.1.4, which does not have the Path definition, yet.
@jcollas The podfile does not specify a specific version for clipper. Any idea why it still uses 5.1.4 instead of the newer version?

**Comment by marcusficner** [comment]
There's also an issue with ProtoBuf.

If you want to use WhirlyGlobe with CocoaPods you have to add these entries to your podfile,
before adding WhirlyGlobe:

```
pod 'clipper', '6.1.3a'
pod 'GoogleProtobuf', '2.5.0'
```

**Comment by jcollas** [comment]
Marcus,

You’re correct, this will fix the problems with the WhirlyGlobe pod.  I can’t update the existing 2.3 pod, but when Steve tags 2.3.1, I’ll submit a new pod with explicit dependencies.

Juan

**Comment by marcusficner** [comment]
Ok, cool. Thanks!
