### ISSUE TITLE
Need sample code for displaying vector mbtiles

### ISSUE THREAD

**Issue by asianrider** [mousebird/WhirlyGlobe#265]
I'm trying to display vector tiles from MapBox, packaged by Mapbox Studio as MBTiles. Here's the code I've tried (this is swift, but you get the idea):

            let mbtilesFile = NSBundle.mainBundle().pathForResource("natural-0-6", ofType: "mbtiles")
            if let fileName = mbtilesFile {
                let style = MapnikStyleSet(forViewC: globeViewController)
                style.loadJsonFile(NSBundle.mainBundle().pathForResource("bright-v4", ofType:"json"))
                style.generateStyles()
                let tileSource = MaplyMBTileSource(MBTiles: fileName)
                let vecTiles = MaplyMapnikVectorTiles(MBTiles: tileSource)
                if vecTiles == nil {
                    println("Can't create tile source with mbtiles")
                    return
                }
                vecTiles.styleDelegate = style;
                let coordSys = tileSource.coordSys // MaplySphericalMercator()
                let pageLayer = MaplyQuadPagingLayer(coordSystem: coordSys, delegate: vecTiles)
                pageLayer.numSimultaneousFetches = 6;
                pageLayer.flipY = false;
                pageLayer.importance = 1024*1024*2;
                pageLayer.useTargetZoomLevel = true;
                pageLayer.singleLevelLoading = true;
                layer = pageLayer

Here's what I get:

    Failed to parse pbf 1/1/0
    Failed to parse pbf 1/1/1
    Failed to parse pbf 1/0/1
    etc..

Any hint ? thanks

**Comment by rastandy** [comment]
For my MBTileSource generated with MapBoxStudio, the problem seems to be related to the [tileData isCompressed] check in this MaplyMapnikVectorTiles method:
- (void)startFetchForTile:(MaplyTileID)tileID forLayer:(MaplyQuadPagingLayer *)layer

In my case, the check return false, but my tiles are compressed. So, if I remove the check, tiles are correctly decompressed and displayed.

I can give you more information needed.

Hope this helps.

**Comment by mousebird** [comment]
I've seen this myself, but I'm traveling and don't have access to my sources.  I believe the problem was the isCompressed check wasn't detecting the variant they were using.  At least for vector.pbf.  

One workaround is to hardwire it temporarily.  I'll integrate the proper fix in a week or so when I'm back.
