### ISSUE TITLE
Artifacts appears when draw geojson filling polygons 

### ISSUE THREAD

**Issue by alasarr** [mousebird/WhirlyGlobe#302]
When a geojson of polygons is drawn using kGeoJSONStyleFill = YES really odd artifacts appears. This artifacts move around the globe when you rotate it.

![issue_artifacts](https://cloud.githubusercontent.com/assets/1161870/7607639/43562a62-f963-11e4-96c3-facd5f2eaeb9.jpg)

This is how I add the GeoJSON:

```
   NSString *fileNameCountries = [[NSBundle mainBundle] pathForResource:@"ne_50m_admin_0_countries" ofType:@"geojson"];
    if (!fileNameCountries){
        return;
    }
    NSData *jsonCountries = [NSData dataWithContentsOfFile:fileNameCountries];
    
    MaplyVectorObject *vectorObject =  [MaplyVectorObject VectorObjectFromGeoJSON:jsonCountries];
    NSDictionary *styles = @{
                             kMaplyColor : [UIColor grayColor],
                             kMaplyFilled : [NSNumber numberWithBool:YES]
                             };
    
    [globe addVectors:@[vectorObject] desc:styles];
```

I've tried with different GeoJSON layers and always happens the same.

**Comment by mousebird** [comment]
This happens with the tessellation.  Because the polygon is actually curved, some of the triangles it creates point far enough away from the normal to show up when the whole area is on the back side of the globe.

There are various solutions to address this in the toolkit.  One is to chop the big features up on a grid and tesselate those individually.

Looking at the documentation I see we only do that for lofted polygons, not regular vectors.

My approach lately has been to do this as a pre-processing step.  So, for example, you can formally tessellate the polygons ahead of time and hand them over to whichever part of the system wants them.  Likewise, we should chop the vectors first, rather than relying on the lofted polygon subsystem to do it.

For now you can try to use lofted polygons, though I suspect that'll be annoying in a different way.  Otherwise, I'll make a note of this for 2.4.

**Comment by alasarr** [comment]
Hi Steve,

Thanks for the answer, it works with lofted polygons but as you pointed out it doesn't looks very pretty. 

I'm going to try chopping the geometries.

**Comment by alasarr** [comment]
Why this issue has been closed? Has it been accomplished or it's an error? I've tried with the latest develop branch and the issue still happens.

**Comment by mousebird** [comment]
Hmm, I guess you're right.

**Comment by sabiland** [comment]
I still see this issue in 2.4 beta 8. Is maybe there any solution to this problem?

**Comment by mousebird** [comment]
It's really a tesselation issue.  Breaking the polygons up finer should help a bit.

**Comment by sabiland** [comment]
Is maybe there a short example how to do this?

**Comment by mousebird** [comment]
No example, but set kMaplySubdivType to kMaplySubdivGrid and try setting kMaplySubdivEpsilon to 0.1 to start and then divide by 2 until you get something that looks good or it gets too slow.

A better solution here would be to have the shader do the backwards normal trick that the line renderer does for the globe.

**Comment by sabiland** [comment]
Ok thx for info, will try this.

**Comment by mousebird** [comment]
There's a shader now that will clear up the remaining problems.
