### ISSUE TITLE
MaplyTexture objects created for MaplyScreenMarkers are never dealloced

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#304]
The problem:
Im using a MaplyQuadPagingLayer to add MaplyScreenMarker objects to the map, the markers have images that are dynamically generated, the generated images are stored in an NSCache.

The first time each image is used it a MaplyTexture is created for it by `- (MaplyTexture *)addTexture:(UIImage *)image imageFormat:(MaplyQuadImageFormat)imageFormat wrapFlags:(int)wrapFlags mode:(MaplyThreadMode)threadMode`

When the app goes into the background, or there is a memory warning the NSCache is cleared, and the paging delegate ends up making new images as needed, these get new MaplyTextures allocated for them, but the old MaplyTextures never get dealloced.

A couple of possible solutions, im not sure if any of these is right:
1. Accept that each image used as a marker will get a MaplyTexture alloced and never freed. This seems problematic. It's nice to not have to live with memory leaks.
2. Keep track of MaplyTexture objects that are in use. It seems like there is already logic to do this, it's just not used with markers. 
3. Compare textures by some value other than a pointer to the original image. Maybe a hash of the png representation. This seems to slow to be practical.

**Comment by mousebird** [comment]
I believe I fixed this one a few months ago.  Which version are you on?

MaplyTexture objects should be cleaned up when they're no longer referenced.  The logic for this was a little complex and there were some bugs early on.  Now, they should be cleaned up for the UIImage and MaplyTexture paths.

I'd advise using MaplyTexture objects directly, rather than assigning UIImage's.  It'll use less memory, since there's no reference to the UIImage and you can do other things, like add them to a texture atlas.

**Comment by alasarr** [comment]
I'm having a similar issue. I'm also using MaplyQuadPagingLayer  in order to draw lots of  MaplyScreenMarker. Everything looks fine but the memory is continuously growing up. 

If I remove the objects the layer disappear but the memory doesn't decrease. I've set a debug trace to dealloc method of the class an it's called. Instruments doesn't report any memory leak.

**Comment by alasarr** [comment]
It doesn't happen with develop branch but this issue https://github.com/mousebird/WhirlyGlobe/issues/264 has come back

**Comment by mousebird** [comment]
Should be fixed in the develop branch.
