### ISSUE TITLE
Multiple vector polygons didSelect

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#348]
The object with the highest drawPriority is not being fired when a user taps on a polygon that overlaps other polygons in the background. This is unexpected user behavior.

**Comment by mousebird** [comment]
I've added the sorting in the selection feedback, but it will only work if kMaplyDrawPriority is set on the vector data itself.  That's unlikely to be the case since kMaplyDrawPriority is set in the description dictionary passed into addVectors:

It might be better just to get all the returns with the globeViewController:allSelect:atLoc:onScreen: delegate and sort through them yourself.
