### ISSUE TITLE
How do quadtree children are related to parents(in terms of size) for SphericalMercator coord. system?

### ISSUE THREAD

**Issue by ambientlight** [mousebird/WhirlyGlobe#391]
So I have a quadPagingLayer. 
For PlateCarree coord. system the tiles of next level are exactly twice shorter then for previous.
But for SphericalMercator coord. system I noticed that this does not hold true.
Level 1 tiles are exactly twice shorter then level 0 ones: __[85.051 latitude width(ur.y-ll.y)  ]__
But Level 2 tiles are shorter near poles and longer near equator. 
__[18.5379 for MaplyTileID(x: 3, y: 3, level: 2)]__
__[66.5133 for MaplyTileID(x: 3, y: 2, level: 2)]__

Can you please give me some insight to how this is done?
I want to be able to compute  __tileIDs__ for all levels for a specific coordinate. 

Thanks.

**Comment by mousebird** [comment]
[Spherical Mercator](https://en.wikipedia.org/wiki/Mercator_projection) is a projected coordinate system.  The quad tree tiles are square in that system, but not so in Latitude/Longitude.  That's what you're seeing

PlateCarree is square in Latitude/Longitude because it just cuts up lat/lon into squares.

**Comment by ambientlight** [comment]
Understood, thanks.
