### ISSUE TITLE
Access mbtiles' internal layer?

### ISSUE THREAD

**Issue by danishin** [mousebird/WhirlyGlobe#393]
First of all, great great work!

I'm trying to implement show/hide country names depending on the user input and to be able to do it, I need to separate layers for country tiles and country names. 

I'm currently using `.mbtiles` as tile source and you can have multiple layers for `.mbtiles` internally that can be shown/hidden using _CartoCSS_ according to zoom levels and whatnot.

Is there a way to access these internal layers of `.mbtiles` from WhirlyGlobe? Or should I create `.mbtiles` for country names only and `addLayer` separately from the main country `.mbtiles`? Then access it?

Please help! Thank you.

-- I'm also wondering if support for WhirlyGlobe in Android is planned for in the near future? I've almost finished my app for iOS now and started looking at Android. It'll be amazing if you can! :+1: :+1:

**Comment by mousebird** [comment]
Thanks.

Those are probably image based MBTiles files, so no, you can't access anything that was in the CartoCSS.  It's all been rendered into 

Making two sets of MBTiles is going to be the fastest and simplest way for you to do this.  In the future I'd recommend vector tiles because you could tease out specific layers of data, but right now that's a complicated approach to pursue on your own.

There is an Android version in development.  It doesn't have MBTiles support as of yet and it's still missing a lot of features.  It'll be in better shape at the end of the month.

**Comment by danishin** [comment]
Yeah that's what I thought. Thanks for the clarification.

As per Android, is it possible to give any really ballpark ETA for the `WhirlyGlobe*` part (not just `Maply*`) so that I can maybe start working on my project and integrate yours in as things progress? But no rush here. I appreciate your work very much:grey_exclamation:

**Comment by mousebird** [comment]
Much of the WhirlyGlobe part should be in place by the end of September.  However, there will be a lot of features missing, so you'll need to check for specific features that you need.

I'll be porting features over on demand (e.g. for cash) as well.
