### ISSUE TITLE
MaplyQuadPagingLayer: MinHeight for ZoomLevel. 

### ISSUE THREAD

**Issue by ambientlight** [mousebird/WhirlyGlobe#395]
I do can retrieve the __targetZoomLevel__ for current view's height settings, it would be good if I can somehow do the reverse - the precise level __height boundaries__ for a specific zoomLevel for  __QuadPagingLayer__.

The scenario is the following: 
I have a __QuadImageTilesLayer__ with __minVis__ at certain height.
Now I need this __minVis__ to be linked up with __QuadPagingLayerDelegate__ __minZoom__,
that is when QuadPagingLayer gets disabled after reaching some height, the QuadImageTilesLayer gets visible. 

I can of course do that with having a timer that would observe the __targetZoomLevel__ and then manually remove/add __QuadImageTilesLayer__ to the maplyViewController, but I believe that should be a better way to do this, since it is a pretty common scenario I guess. 

One way would be an ability for __QuadImageTilesLayer__ to specify the __minVis__ in terms of zoom level instead of __minVis__ in terms of height.

**Comment by mousebird** [comment]
The Mapnik equivalent is in there as heightForMapScale:
Unfortunately, Mapnik's scales are not quite the same as zoom levels.

I make use of zoom levels in the Mapbox GL Style sheet parser, but that doesn't have the logic you want.  Since it's being driven by a quad paging layer and the geometry for each tile is basically unique, you don't really need it there.

**Comment by ambientlight** [comment]
Understood. Thanks.
