### ISSUE TITLE
Is there a way to make a MaplyQuadPagingLayer skip some zoom levels?

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#488]
Many types of data change per zoom level, but they don't change on every zoom level. It would be great to be able to make a layer only load certain zoom levels by setting something like layer.zoomLevels =  @[@1, @3, @6, @9, @12, @15];

Is there a way to do this currently?

**Comment by mousebird** [comment]
Nope, but it's an interesting idea.

I'd imagine it's doable, but it complicates the internal QuadPagingLayer logic.  Though it does dovetail with an idea I've had for uniquely identified assets loaded in the QuadPagingLayer.  For example levels 4 and 5 might use asset aef8a9 so reference count it rather than reloading it each time.

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>
