### ISSUE TITLE
Swift compiler cannot find STL header

### ISSUE THREAD

**Issue by cgudrian** [mousebird/WhirlyGlobe#544]
I've set up [a simple single view iPhone application](https://github.com/cgudrian/WhirlyGlobeSwift) using the Xcode template that uses the WhirlyGlobe pod from the 2.4.1 development branch. Compilation using Xcode 7.2.1 fails with the error

    'map' file not found in ActiveModel.h

**Comment by mousebird** [comment]
It looks like those aren't necessary since that's just a protocol.  You can work around the problem by commenting the map and list includes out.  I'll fix it in the regular repo.

**Comment by cgudrian** [comment]
That's what I did at first. But then the file `Identifiable.h` fails to compile because the 'set' header could not be found. However `std::set` is used in a typedef so commenting out the `#include` won't help in this case.

**Comment by mousebird** [comment]
Commenting out the ActiveModel header might work temporarily.

**Comment by mousebird** [comment]
Okay, looking at this a bit closer.  I guess the issue is a combination of Swift and Pods.

ActiveModel.h isn't being pulled in by WhirlyGlobeComponent.h or MaplyComponent.h.  Those are the top level header files and they avoid exposing the lower level WhirlyGlobeLib headers.

So the question is, why is a Swift module pulling in ActiveModel.h?  I'm not that familiar with how Swift figures out which headers to pull in.  José can you look at this?

**Comment by jmnavarro** [comment]
I image it's inside the umbrella header because it's a public header. 

I'll check it out in a couple of days

**Comment by mousebird** [comment]
That's unfortunate.  Maybe we could tell if it's a .mm file they're compiling and only include the WhirlyGlobeLib headers in that case.

**Comment by jmnavarro** [comment]
Hey @cgudrian 

Can you try again with the branch "develop_2_4_1" and let us know the result?

**Comment by mousebird** [comment]
I think we've got this now.  If it's still here, just reopen.
