### ISSUE TITLE
WMTS Basic Authentication

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [mousebird/WhirlyGlobe#709]
I'm attempting to connect to authenticated WMTS services and to do so I need to add the `Authorization` header to NSURLRequsts in `MaplyWMSTileSource.imageForTile` but I don't see any way to do so.

Is there any way to do this that I'm not seeing or is it a planned feature?   If not I'll look at doing a PR sometime in the next few weeks.

As a work around I wrote a custom `MaplyTileSource` and filled out the `imageForTile` with a URL request that fetches the tiles.  It works however it's less than ideal because I need to use semaphores to halt the thread until the request is complete.  Is there a better way of providing asynchronous Tile source?

**Comment by mousebird** [comment]
We'd like to provide more support from WMTS.  However, most people seem to dig out the tile URLs they need and then just query directly, working around the problem.  :-/

Instead of using MaplyTileSource, could you subclass MapyRemoteTileInfo?
I see that requestForTile: returns an NSURLRequest so presumably you could modify the header right there.
