### ISSUE TITLE
[Android] Strange side effect of LayoutImportance = MAX_VALUE

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#744]
Since the last fix re layout engine, there is a strange behaviour and I am not sure it is a bug or the famous "unexpected behaviour".

Basically, when either not setting LabelInfo.layoutImportance or setting it to Float.MAX_VALUE, _LabelInfo.layoutPlacement_ is ignored.

Labels do indeed shown regardless of other labels, but I cannot control their placement.

When I set a value, labels have to compete for space with other labels and between labels of same importance, but they display at the right place.

This is not what I expected.
I expected LabelInfo.layoutImportance = Float.MAX_VALUE to disable competition for space, but not block layout placement.

Is it the intended behaviour ?
This seems a bit extreme.

Thanks,
JM

**Comment by mousebird** [comment]
That is a little odd now that I think about it.  It's all logical, but confusing.

Setting the layoutImportance to MAXFLOAT just takes the object out of the layout engine entirely.  Since the layoutPlacement is implemented in the layout engine, you get no placement.

My suggestion is to use the offset in the ScreenLabel to achieve the same effect.

**Comment by jmcazaux** [comment]
Using offset if going to be difficult for thing like centering or right aligning (left ?) as it would require knowing the size of label on screen.

This can be done using Android Paint, but as the SDK does not fully match that (#698), this could lead to awkward placements.

As well, I am not sure you will want to let layoutImportance initialized to MAX_FLOAT as it is going to break things for people (people who never set layoutImportance to a specific value but used layoutPlacement in a satisfactory way will now see their maps broken).

JM

**Comment by mousebird** [comment]
That's true, but the semantics are a little weird for using it outside the layout engine.  If the developer sets multiple layout options which should we pick?  Well, we could probably fix the first one and call it a day.

So I do have this workaround where you can set the layoutSize which lets objects get run through the layout engine, but not have any size.  That would halfway work, but it wouldn't get the placement right.

I wonder if a layoutTransparent setting would do the trick.  If set, we run it through the layout engine, but it's otherwise transparent in that it doesn't block or get blocked.

**Comment by jmcazaux** [comment]
layoutTransparent is probably what people expect when they read "disable layout engine".

In a nutshell what a developper would want:
- as a developper (and powers that be in my app) I want this label/marker to be displayed regardless of other labels / markers
- I take full responsibility if overlap happens in this situation

Another option would be to stop the competition for space when 2 objects have the same importance  and display both (instead of removing one randomly as it happens today). 
But I feel this would feel more broken (as not resulting from a conscious decision) than layoutTransparent.
