### ISSUE TITLE
Maximum zoom level for a TileSource stuck at 22

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [mousebird/WhirlyGlobe#862]
I'm looking at Maply as a potential conduit for extremely high resolution imagery.  Think cm level, leaf on the sidewalk level.  Most major mapping engines don't support this, presumably because it's well past the resolution of it's satellite imagery.

I wrote a quick test to see how deeply you can zoom by rendering out tiles with x,y,zoom labels:
https://gist.github.com/ChrisLowe-Takor/af05f8ac3b207de4dd61aa6ad6a04fa3

The `maxZoom` is set to an abitratily large number (32) but the engine only goes as far as 22.

I'm curious if possible to go deeper than this.   [This issue](https://github.com/mousebird/WhirlyGlobe/issues/57) from a couple of years ago mentions it brushes up against the inaccuracies of floating point numbers but goes on to say it is something that might be possible just with increasing jitteriness.

**Comment by mousebird** [comment]
Parts of this appear in different aviation apps.  So most of the pieces are probably there somewhere.

The specific [issue here](https://github.com/mousebird/WhirlyGlobe/issues/57) was that geometry was (and is) stored in floating point.  I corrected the problem by generating an offset for groups of drawables.  So as you zoom in it decides if it has enough resolution and, if not, it makes a new offset and puts new drawables in there.

Which means the rendering side can handle it.  But the generation side maybe not.  If geometry is generated in floating point it's going to get a little wonky down that close.  The solution there is to work in doubles up until we generate drawables with the offset.  We're mostly doing that, I think, but I bet there's a spot or two where we're not.

Then you've got the gestures.  We moved those to doubles a while ago, but I couldn't say for sure that we rooted out all the 32 bit floating point logic.

Last, there's the view matrix logic itself.  Now that's mostly double matrices, but the near and far clipping planes are in 32 bit floating point.  We work around this by adapting the "zoom" at high levels and messing with other values to simulate getting closer to the surface.  So that will work up to a point.

Oh, and there's also the level loading.  Best to use multi-level loading and not have it start loading at level 0.  That's new, but it would make a big difference in time.

All of this was tuned for the most extreme use case, probably an aviation customer.  But not *this* extreme.  To do this right we'd need to trace through the logic and see what's holding things up.

This is the sort of thing I do for support customers or you could give it a try yourself.
