### ISSUE TITLE
Local tile fetching gets backed up by remote fetches backing up

### ISSUE THREAD

**Issue by brandonreavis** [mousebird/WhirlyGlobe#866]
Right now TileQuadLoader has an `isReady` method that lets the QuadDisplayLayer know when to wait for requests from the tilesource to finish before making another request. This works fine, but if you are offline or the network is bad it forces all local tile fetches to wait for the remote fetches to timeout first. What is the best way to decouple these so that there could be something like `maxSimultaneousLocalFetches` and `maxSimultaneousRemoteFetches`?

The place where this becomes a pain is if you are offline, and lets say you have tiles cached from zoom 0 to 14, and then the user zooms into 15, and then back out. Tile loading is then stuck for 10 seconds or however long the timeout is even though the cached tiles are available should be ready to be shown.

So there are two possible fixes I see: 
1) Separating `maxSimultaneousFetches` to `maxSimultaneousLocalFetches` and `maxSimultaneousRemoteFetches`, and restructuring `QuadTileLayer.evalStep` to ask TileQuadLoader if it is ready to load a particular tile, rather than a simple `isReady` call.

2) Abort pending fetches from remote tilesources if the tile isn't being displayed anymore. This would be ideal, but I don't know if its a great idea to *immediately* abort requests that aren't shown anymore (ie. a user zooming in and out quickly)

Your thoughts?

**Comment by mousebird** [comment]
Aborting the requests is a good solution.  Users do tend to react to data not loading by zooming back out.  I've starting take aborts into account in other places, like Android tile sources.

As for the local vs remote handling in the paging logic, I kind of like the idea, but that stuff is massively complex.

At some point I need to break out the individual frame loading, so that might be a good time to revisit this.

**Comment by mousebird** [comment]
Completely rewrote the loading/sampling architecture.
