### ISSUE TITLE
A problem with vectors on globe (Android SDK)

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#997]
When I rotate a globe I see vector data from the other side of the globe.
Please provide a solution.

![screenshot_20170906-202418](https://user-images.githubusercontent.com/10597798/30153839-907a2a92-93c0-11e7-9164-efc822a5fe9a.png)

**Comment by rghosh0** [comment]
I am seeing something similar in iOS, in the AutoTester "Vector Style Test" from branch develop.

![simulator screen shot sep 11 2017 2 51 04 pm](https://user-images.githubusercontent.com/1896717/30291427-ddc7c050-9700-11e7-97c3-6fb5c70f0f10.png)

**Comment by rghosh0** [comment]
I looked into this a little more: I was wondering why the Vectors Test didn't have this problem but the Vector Style Test did... if I explicitly called tesselate on the MaplyVectorObject objects in VectorsTestCase, then I see all kinds of weird slivers everywhere. Which beats me, because I figures tesselate was being called somewhere regardless of whether it's explicitly called at the top level.

**Comment by mousebird** [comment]
That's true, but they're being tessellated differently.
I sent Anton a workaround for Android.  The trick is to use a smarter shader on the polygons that handles the backside normal case.  The problem is on Android we don't expose the default shaders.  We either use the one we have or we let the developer make their own.
